### ISSUE TITLE
Bootstrap Snippet

### ISSUE THREAD

**Issue by Ispeakmusic** [JavierBmrg/atom-hosted-libs#4]
The Bootstrap(css) snippet is not working properly. Please change the link to: 
https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css

thank you guys :)

**Comment by JavierBmrg** [comment]
Hello @Ispeakmusic !

Thanks for notifying the problem. It's fixed :)
